service: weshare-backend
frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  environment:
    BUCKET_NAME: !Ref FileBucket
    BASE_URL: https://${self:custom.domainName}

custom:
  domainName: weshare.click

functions:
  createShare:
    handler: share-handler.handleEvent
    events:
      - httpApi:
          method: POST
          path: "/"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource:
          - !Sub "arn:aws:s3:::${FileBucket}/shares/*"
      - Effect: Allow
        Action:
          - s3:ListBucket
        Resource:
          - !Sub "arn:aws:s3:::${FileBucket}"

  download:
    handler: download.handleEvent
    events:
      - httpApi:
          method: GET
          path: "/{id}"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource:
          - !Sub "arn:aws:s3:::${FileBucket}/shares/*"

resources:
  Resources:
    CustomDomain:
      Type: AWS::ApiGatewayV2::DomainName
      Properties:
        DomainName: ${self:custom.domainName}
        DomainNameConfigurations:
          - CertificateArn: ${cf:domain-${sls:stage}.DomainCertArn}

    DomainRecordSet:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId: ${cf:domain-${sls:stage}.PublicHostedZone}
        RecordSets:
          - Name: ${self:custom.domainName}
            Type: A
            AliasTarget:
              DNSName: !GetAtt CustomDomain.RegionalDomainName
              HostedZoneId: !GetAtt CustomDomain.RegionalHostedZoneId
          - Name: ${self:custom.domainName}
            Type: AAAA
            AliasTarget:
              DNSName: !GetAtt CustomDomain.RegionalDomainName
              HostedZoneId: !GetAtt CustomDomain.RegionalHostedZoneId

    CustomDomainPathMapping:
      Type: AWS::ApiGatewayV2::ApiMapping
      Properties:
        ApiId: !Ref HttpApi
        ApiMappingKey: "share"
        DomainName: !Ref CustomDomain
        Stage: !Ref HttpApiStage

    FileBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${file(./unique-bucket-name.cjs):bucketName}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        NotificationConfiguration:
          EventBridgeConfiguration:
            EventBridgeEnabled: true
